version: 2.1
orbs:
  commitlint: conventional-changelog/commitlint@1.0.0
  node: circleci/node@5.1.0
alias:
  - &defaults
    docker:
      - image: cimg/node:18.12.1
    executor: node/default
jobs:
  main-job:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages
      - run: npm test
      - run: npx --no -- semantic-release
workflows:
  version: 2
  commitlint:
    jobs:
      - commitlint/lint:
          target-branch: master
          filters:
            branches:
                ignore:
                  - master
  main-workflow:
    jobs:
      - main-job
